Replace tblink
TBfighters/tbfightersdotorg pull request #95
Opened 2024-04-02 03:35 UTC by matt598

# Description

# Type of change

- [ ] Correction (typos, outdated links, etc.)
- [ ] Updated content (New CTA, updated wording, etc.)
- [ ] New content/feature (new page, new section, etc.)
- [ ] Documentation update

# Misc Notes

2024-04-03 22:14 UTC, YummyOreo approved these changes

2024-04-08 13:41 UTC, Nolram12345 requested changes
The reaon TBlink is used so we don't have to explicitly hardcode links, which may change in the future or are generally out of our control. They also allow for easier sharing across social media.
I personally would not approve this for the time being because I don't see the point.

2024-04-08 14:19 UTC, DFTBA-Shalom commented
> The reaon TBlink is used so we don't have to explicitly hardcode links, which may change in the future or are generally out of our control. They also allow for easier sharing across social media. I personally would not approve this for the time being because I don't see the point.

In this particular situation (where we're linking to the petition) I don't really see it being moved, since that would be bad for MSF. I think the reason Matt would prefer to use direct links instead of redirects when we hyperlink is to have as smooth a process to the end site as possible, to increase user retention. We do something similar in other places (like the templates document link, which could also be linked to with tbfighter.link/templates).
If it was moved wouldn't it be just as easy to change on the site as changing the redirect? Obviously the redirect is used in other places like graphics and social media, so it is useful, just not sure this is its best use case.

2024-04-08 15:05 UTC, Nolram12345 commented
Hmm... yeah, in this particular case it's probably safe to directly link, but generally we should prefer TBlink links over links to dynamic content as it means we can adapt and change links as necessary after creation.

2024-04-15 15:35 UTC, devoeas approved these changes

2024-04-15 15:35 UTC, merged